// <auto-generated />
using System;
using CampusConnectAPI.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CampusConnectAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CampusConnectAPI.Models.Campus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EmailDomain")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Campuses");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Community", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CampusId")
                        .HasColumnType("int");

                    b.Property<sbyte?>("IsPrivate")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CampusId");

                    b.ToTable("Communities");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.ForumThread", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CommunityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CommunityId");

                    b.HasIndex("CreatedById");

                    b.ToTable("ForumThreads");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Login", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("Logins");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedById")
                        .HasColumnType("int");

                    b.Property<int>("ThreadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ThreadId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Major")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.ProfileClub", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.HasKey("ProfileId", "ClubId");

                    b.HasIndex("ClubId");

                    b.ToTable("ProfileClubs");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.ProfileCourse", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.HasKey("ProfileId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("ProfileCourses");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Reputation", b =>
                {
                    b.Property<int>("ProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("ProfileId", "Category");

                    b.ToTable("Reputations");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Club", b =>
                {
                    b.HasOne("CampusConnectAPI.Models.Campus", "Campus")
                        .WithMany("Clubs")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Community", b =>
                {
                    b.HasOne("CampusConnectAPI.Models.Campus", "Campus")
                        .WithMany("Communities")
                        .HasForeignKey("CampusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campus");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.ForumThread", b =>
                {
                    b.HasOne("CampusConnectAPI.Models.Community", "Community")
                        .WithMany("ForumThreads")
                        .HasForeignKey("CommunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnectAPI.Models.Profile", "CreatedBy")
                        .WithMany("ForumThreads")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Community");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Login", b =>
                {
                    b.HasOne("CampusConnectAPI.Models.Profile", "Profile")
                        .WithOne("Login")
                        .HasForeignKey("CampusConnectAPI.Models.Login", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Post", b =>
                {
                    b.HasOne("CampusConnectAPI.Models.Profile", "CreatedBy")
                        .WithMany("Posts")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnectAPI.Models.ForumThread", "ForumThread")
                        .WithMany("Posts")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("ForumThread");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.ProfileClub", b =>
                {
                    b.HasOne("CampusConnectAPI.Models.Club", "Club")
                        .WithMany("ProfileClubs")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnectAPI.Models.Profile", "Profile")
                        .WithMany("ProfileClubs")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.ProfileCourse", b =>
                {
                    b.HasOne("CampusConnectAPI.Models.Course", "Course")
                        .WithMany("ProfileCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CampusConnectAPI.Models.Profile", "Profile")
                        .WithMany("ProfileCourses")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Reputation", b =>
                {
                    b.HasOne("CampusConnectAPI.Models.Profile", "Profile")
                        .WithMany("Reputations")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Campus", b =>
                {
                    b.Navigation("Clubs");

                    b.Navigation("Communities");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Club", b =>
                {
                    b.Navigation("ProfileClubs");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Community", b =>
                {
                    b.Navigation("ForumThreads");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Course", b =>
                {
                    b.Navigation("ProfileCourses");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.ForumThread", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("CampusConnectAPI.Models.Profile", b =>
                {
                    b.Navigation("ForumThreads");

                    b.Navigation("Login");

                    b.Navigation("Posts");

                    b.Navigation("ProfileClubs");

                    b.Navigation("ProfileCourses");

                    b.Navigation("Reputations");
                });
#pragma warning restore 612, 618
        }
    }
}
